//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : Chart1


#ifndef RTW_HEADER_Chart1_private_h_
#define RTW_HEADER_Chart1_private_h_
#include "rtwtypes.h"

// Includes for objects with custom storage classes.
#include "defines.h"

// Imported (extern) block signals
extern uint8_T state_Inverter;         // '<Root>/state_Inverter'
extern uint8_T din_RunEnter;           // '<Root>/din_RunEnter'

#endif                                 // RTW_HEADER_Chart1_private_h_

//
//  [EOF]

