//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : Chart1


#ifndef RTW_HEADER_Chart1_types_h_
#define RTW_HEADER_Chart1_types_h_
#endif                                 // RTW_HEADER_Chart1_types_h_

//
//  [EOF]

