function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "MX_Gateway"};
	this.sidHashMap["MX_Gateway"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "MX_Gateway:30998"};
	this.sidHashMap["MX_Gateway:30998"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "MX_Gateway:31112"};
	this.sidHashMap["MX_Gateway:31112"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S1>/state_System"] = {sid: "MX_Gateway:31005"};
	this.sidHashMap["MX_Gateway:31005"] = {rtwname: "<S1>/state_System"};
	this.rtwnameHashMap["<S1>/Bus Creator"] = {sid: "MX_Gateway:31157"};
	this.sidHashMap["MX_Gateway:31157"] = {rtwname: "<S1>/Bus Creator"};
	this.rtwnameHashMap["<S1>/Bus Selector17"] = {sid: "MX_Gateway:31058"};
	this.sidHashMap["MX_Gateway:31058"] = {rtwname: "<S1>/Bus Selector17"};
	this.rtwnameHashMap["<S1>/Chart"] = {sid: "MX_Gateway:31112"};
	this.sidHashMap["MX_Gateway:31112"] = {rtwname: "<S1>/Chart"};
	this.rtwnameHashMap["<S1>/Data Type Conversion"] = {sid: "MX_Gateway:31061"};
	this.sidHashMap["MX_Gateway:31061"] = {rtwname: "<S1>/Data Type Conversion"};
	this.rtwnameHashMap["<S1>/Data Type Conversion1"] = {sid: "MX_Gateway:31096"};
	this.sidHashMap["MX_Gateway:31096"] = {rtwname: "<S1>/Data Type Conversion1"};
	this.rtwnameHashMap["<S1>/targetSpeed3"] = {sid: "MX_Gateway:31106"};
	this.sidHashMap["MX_Gateway:31106"] = {rtwname: "<S1>/targetSpeed3"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "MX_Gateway:31159"};
	this.sidHashMap["MX_Gateway:31159"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>:3"] = {sid: "MX_Gateway:31112:3"};
	this.sidHashMap["MX_Gateway:31112:3"] = {rtwname: "<S2>:3"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "MX_Gateway:31112:1"};
	this.sidHashMap["MX_Gateway:31112:1"] = {rtwname: "<S2>:1"};
	this.rtwnameHashMap["<S2>:2"] = {sid: "MX_Gateway:31112:2"};
	this.sidHashMap["MX_Gateway:31112:2"] = {rtwname: "<S2>:2"};
	this.rtwnameHashMap["<S2>:4"] = {sid: "MX_Gateway:31112:4"};
	this.sidHashMap["MX_Gateway:31112:4"] = {rtwname: "<S2>:4"};
	this.rtwnameHashMap["<S2>:6"] = {sid: "MX_Gateway:31112:6"};
	this.sidHashMap["MX_Gateway:31112:6"] = {rtwname: "<S2>:6"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
