//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : Chart


#ifndef RTW_HEADER_Chart_types_h_
#define RTW_HEADER_Chart_types_h_

// Forward declaration for rtModel
typedef struct tag_RTM_Chart_T RT_MODEL_Chart_T;

#endif                                 // RTW_HEADER_Chart_types_h_

//
//  [EOF]

