//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : ElectricAutomation


#ifndef RTW_HEADER_ElectricAutomation_h_
#define RTW_HEADER_ElectricAutomation_h_
#include <string.h>
#ifndef ElectricAutomation_COMMON_INCLUDES_
# define ElectricAutomation_COMMON_INCLUDES_
#include "rtwtypes.h"
#endif                                 // ElectricAutomation_COMMON_INCLUDES_

#include "ElectricAutomation_types.h"

// Child system includes
#include "mod_System.h"

// Macros for accessing real-time model data structure

// user code (top of header file)
#include "cdata.h"
#include "ap_can.h"
#include "SendMsgNow.h"
#include "ap_eeprom.h"
#include "ap_bservice_CAN04.h"

// Block states (auto storage) for system '<Root>'
typedef struct {
  struct {
    uint_T is_c5_ElectricAutomation:2; // '<S1>/Chart'
    uint_T is_active_c5_ElectricAutomation:1;// '<S1>/Chart'
  } bitsForTID1;
} D_Work_ElectricAutomation;

// External inputs (root inport signals with auto storage)
typedef struct {
  boolean_T outNMCStatus;              // '<Root>/outNMCStatus'
  CANOpenMsgRPDO1 CANOpenMsgRPDO1_jpnx;// '<Root>/CANOpenMsgRPDO1'
  test test_n13h;                      // '<Root>/test'
} ExternalInputs_ElectricAutomati;

// External outputs (root outports fed by signals with auto storage)
typedef struct {
  testOut Out1_jdzy;                   // '<Root>/Out1'
} ExternalOutputs_ElectricAutomat;

// Real-time Model Data Structure
struct tag_RTM_ElectricAutomation {
  //
  //  Timing:
  //  The following substructure contains information regarding
  //  the timing information for the model.

  struct {
    struct {
      uint8_T TID[2];
    } TaskCounters;
  } Timing;
};

// Block states (auto storage)
extern D_Work_ElectricAutomation ElectricAutomation_DWork;

#ifdef __cplusplus

extern "C" {

#endif

  // External inputs (root inport signals with auto storage)
  extern ExternalInputs_ElectricAutomati ElectricAutomation_U;

  // External outputs (root outports fed by signals with auto storage)
  extern ExternalOutputs_ElectricAutomat ElectricAutomation_Y;

#ifdef __cplusplus

}
#endif

//
//  Exported Global Signals
//
//  Note: Exported global signals are block signals with an exported global
//  storage class designation.  Code generation will declare the memory for
//  these signals and export their symbols.
//

extern uint16_T Out2;                  // '<S1>/Data Type Conversion'
extern uint8_T cmdInverter;            // '<S1>/Chart'
extern boolean_T Out1;                 // '<S1>/Data Type Conversion1'

#ifdef __cplusplus

extern "C" {

#endif

  // Model entry point functions
  extern void ElectricAutomation_initialize(void);
  extern void ElectricAutomation_step(void);

#ifdef __cplusplus

}
#endif

// Real-time Model object
#ifdef __cplusplus

extern "C" {

#endif

  extern RT_MODEL_ElectricAutomation *const ElectricAutomation_M;

#ifdef __cplusplus

}
#endif

//-
//  The generated code includes comments that allow you to trace directly
//  back to the appropriate location in the model.  The basic format
//  is <system>/block_name, where system is the system number (uniquely
//  assigned by Simulink) and block_name is the name of the block.
//
//  Note that this particular code originates from a subsystem build,
//  and has its own system numbers different from the parent model.
//  Refer to the system hierarchy for this subsystem below, and use the
//  MATLAB hilite_system command to trace the generated code back
//  to the parent model.  For example,
//
//  hilite_system('MX_Gateway/MX_Gtwy_Control/System/ElectricAutomation')    - opens subsystem MX_Gateway/MX_Gtwy_Control/System/ElectricAutomation
//  hilite_system('MX_Gateway/MX_Gtwy_Control/System/ElectricAutomation/Kp') - opens and selects block Kp
//
//  Here is the system hierarchy for this model
//
//  '<Root>' : 'MX_Gateway/MX_Gtwy_Control/System'
//  '<S1>'   : 'MX_Gateway/MX_Gtwy_Control/System/ElectricAutomation'
//  '<S2>'   : 'MX_Gateway/MX_Gtwy_Control/System/ElectricAutomation/Chart'


//-
//  Requirements for '<Root>': ElectricAutomation

#endif                                 // RTW_HEADER_ElectricAutomation_h_

//
//  [EOF]

