//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : ElectricAutomation


#ifndef RTW_HEADER_ElectricAutomation_types_h_
#define RTW_HEADER_ElectricAutomation_types_h_
#include "rtwtypes.h"
#ifndef DEFINED_TYPEDEF_FOR_CANOpenMsgRPDO1_
#define DEFINED_TYPEDEF_FOR_CANOpenMsgRPDO1_

typedef struct {
  boolean_T outNMCStatus;
  boolean_T outNEBStatus;
  boolean_T outA3;
  boolean_T outA4;
  boolean_T outA5;
  boolean_T outA6;
  boolean_T outA10;
  boolean_T outA13;
  boolean_T outA19;
  boolean_T sensAckInProg;
  boolean_T sensAckOK;
  boolean_T watchdogBit;
  uint8_T statusByte;
  uint8_T anin01;
  uint8_T anin02;
  uint8_T actualCurrent;
  int16_T actualSpeed;
} CANOpenMsgRPDO1;

#endif

#ifndef DEFINED_TYPEDEF_FOR_test_
#define DEFINED_TYPEDEF_FOR_test_

typedef struct {
  boolean_T In1;
  boolean_T In2;
} test;

#endif

#ifndef DEFINED_TYPEDEF_FOR_testOut_
#define DEFINED_TYPEDEF_FOR_testOut_

typedef struct {
  boolean_T Out1;
  uint16_T Out2;
} testOut;

#endif

// Forward declaration for rtModel
typedef struct tag_RTM_ElectricAutomation RT_MODEL_ElectricAutomation;

#endif                                 // RTW_HEADER_ElectricAutomation_types_h_ 

//
//  [EOF]

