//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : ElectricAutomation


#include "mod_System.h"

// Include model header file for global data
#include "ElectricAutomation.h"
#include "ElectricAutomation_private.h"

// Named constants for Chart: '<S1>/Chart'
#define ElectricAuto_IN_NO_ACTIVE_CHILD ((uint8_T)0U)
#define ElectricAutom_IN_PreOperational ((uint8_T)2U)
#define ElectricAutomati_IN_Operational ((uint8_T)1U)

// System initialize for atomic system: '<Root>/ElectricAutomation'
void Electri_ElectricAutomation_Init(void)
{
  // SystemInitialize for Chart: '<S1>/Chart'
  ElectricAutomation_DWork.bitsForTID1.is_active_c5_ElectricAutomation = 0U;
  ElectricAutomation_DWork.bitsForTID1.is_c5_ElectricAutomation =
    ElectricAuto_IN_NO_ACTIVE_CHILD;
}

// Output and update for atomic system: '<Root>/ElectricAutomation'
void ElectricAuto_ElectricAutomation(void)
{
  // Chart: '<S1>/Chart' incorporates:
  //   Inport: '<Root>/din_RunEnter'

  // Gateway: ElectricAutomation/Chart
  // During: ElectricAutomation/Chart
  if ((uint32_T)
      ElectricAutomation_DWork.bitsForTID1.is_active_c5_ElectricAutomation == 0U)
  {
    // Entry: ElectricAutomation/Chart
    ElectricAutomation_DWork.bitsForTID1.is_active_c5_ElectricAutomation = 1U;

    // Entry Internal: ElectricAutomation/Chart
    // Transition: '<S2>:2'
    ElectricAutomation_DWork.bitsForTID1.is_c5_ElectricAutomation =
      ElectricAutom_IN_PreOperational;
  } else if (ElectricAutomation_DWork.bitsForTID1.is_c5_ElectricAutomation ==
             ElectricAutomati_IN_Operational) {
    // During 'Operational': '<S2>:3'
    if ((int32_T)din_RunEnter == 0) {
      // Transition: '<S2>:6'
      cmdInverter = GO_PRE_OPERATIONAL;
      ElectricAutomation_DWork.bitsForTID1.is_c5_ElectricAutomation =
        ElectricAutom_IN_PreOperational;
    }
  } else {
    // During 'PreOperational': '<S2>:1'
    if ((int32_T)din_RunEnter == 1) {
      // Transition: '<S2>:4'
      cmdInverter = GO_OPERATIONAL;
      ElectricAutomation_DWork.bitsForTID1.is_c5_ElectricAutomation =
        ElectricAutomati_IN_Operational;
    }
  }

  // End of Chart: '<S1>/Chart'

  // DataTypeConversion: '<S1>/Data Type Conversion' incorporates:
  //   Inport: '<Root>/CANOpenMsgRPDO1'

  Out2 = (uint16_T)ElectricAutomation_U.CANOpenMsgRPDO1_jpnx.actualSpeed;

  // DataTypeConversion: '<S1>/Data Type Conversion1' incorporates:
  //   Inport: '<Root>/CANOpenMsgRPDO1'

  Out1 = ElectricAutomation_U.CANOpenMsgRPDO1_jpnx.outNMCStatus;
}

//
//  [EOF]

