//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : ElectricAutomation


#ifndef RTW_HEADER_mod_System_h_
#define RTW_HEADER_mod_System_h_
#ifndef ElectricAutomation_COMMON_INCLUDES_
# define ElectricAutomation_COMMON_INCLUDES_
#include "rtwtypes.h"
#endif                                 // ElectricAutomation_COMMON_INCLUDES_

#include "ElectricAutomation_types.h"

extern void Electri_ElectricAutomation_Init(void);
extern void ElectricAuto_ElectricAutomation(void);

#endif                                 // RTW_HEADER_mod_System_h_

//
//  [EOF]

