%Function for loading function signals to the workspace
%
% Name: CreateFunction.m
%
% Copyright 2008 Bobcat Company as an unpublished work. 
% All Rights Reserved.
%
% The information contained herein is confidential property of Bobcat
% Company. The use, copying, transfer or disclosure of such information is
% prohibited except by express written agreement with Bobcat Company.
%	
% First written on 14 May 2008 by Al Liebel.
%
% Description:
%   Function to create defines for constant model parameters in the
%   workspace. Also defines the autogenerated header file.
%   Name - Signal Name
%   Function - Function name
%   Type - Data Type for data passed by function call
%   Size - Data Size (array size) passed by function call
%   Initial Value - Function is called during init, initial value passed by
%   function call
%   HeaderFile - Header file for function declaration
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function CreateFunction(Name, Function, Type, Size, InitialValue, HeaderFile)
    Name.RTWInfo.StorageClass = 'Custom';
    Name.RTWInfo.CustomStorageClass = 'GetSet';
    Name.DataType = Type;
    Name.Dimensions = Size;
    Name.InitialValue = InitialValue;
    Name.RTWInfo.CustomAttributes.HeaderFile = HeaderFile;
    Name.RTWInfo.CustomAttributes.GetFunction = 'Unused';
    Name.RTWInfo.CustomAttributes.SetFunction = Function;
end