%Function for loading defines to workspace
%
% Name: CreateDefine.m
%
% Copyright 2008 Bobcat Company as an unpublished work. 
% All Rights Reserved.
%
% The information contained herein is confidential property of Bobcat
% Company. The use, copying, transfer or disclosure of such information is
% prohibited except by express written agreement with Bobcat Company.
%	
% First written on 14 May 2008 by Al Liebel.
%
% Description:
%   Function to create defines for constant model parameters in the
%   workspace. Also defines the autogenerated header file.
%   Name - Parameter Name (i.e. OORH)
%   Value - Workspace value to be assigned to parameter
%   CustStrCls - Custom Storage Class name for define parameter
%   HeaderFile - Name for autogenerated header file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function CreateDefine(Name, Value, CustStrCls, HeaderFile)
    Name.RTWInfo.StorageClass = 'Custom';
    Name.RTWInfo.CustomStorageClass = CustStrCls;
    Name.RTWInfo.CustomAttributes.HeaderFile = HeaderFile;
    Name.Value = Value;
end