//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gtwy_Control


#ifndef RTW_HEADER_mod_System_h_
#define RTW_HEADER_mod_System_h_
#ifndef MX_Gtwy_Control_COMMON_INCLUDES_
# define MX_Gtwy_Control_COMMON_INCLUDES_
#include "rtwtypes.h"
#endif                                 // MX_Gtwy_Control_COMMON_INCLUDES_

#include "MX_Gtwy_Control_types.h"

extern void MX_Gtwy_C_Auto_Idle_Enable_Init(void);
extern void MX_Gtwy_Contro_Auto_Idle_Enable(void);
extern void MX_Gtwy_Control_AutoIdle_Init(void);
extern void MX_Gtwy_Control_AutoIdle(void);
extern void MX_Gtwy_Control_Aux_Enable_Init(void);
extern void MX_Gtwy_Control_Aux_Enable(void);
extern void MX_Gtwy_Contr_CAN_Throttle_Init(void);
extern void MX_Gtwy_Con_CAN_Throttle_Update(void);
extern void MX_Gtwy_Control_CAN_Throttle(void);
extern void MX_Gtwy_C_Controller_State_Init(void);
extern void MX_Gtwy_Contro_Controller_State(void);
extern void MX_Gtwy_Control_Derate_Init(void);
extern void MX_Gtwy_Control_Derate(void);
extern void MX_Gtwy_Co_EMEAControlMode_Init(void);
extern void MX_Gtwy_Control_EMEAControlMode(void);
extern void MX_Gtwy_ElectricAutomation_Init(void);
extern void MX_Gtwy_Cont_ElectricAutomation(void);
extern void MX_Gtwy_Control_Engine_Init(void);
extern void MX_Gtwy_Control_Engine(void);
extern void MX_Gtwy_Cont_Keyless_Entry_Init(void);
extern void MX_Gtwy_Con_Keyless_Entry_Reset(void);
extern void MX_Gtwy_C_Keyless_Entry_Disable(void);
extern void MX_Gtwy_Control_Keyless_Entry(void);
extern void MX_Gtwy_Cont_Keyless_Start_Init(void);
extern void MX_Gtwy_Control_Keyless_Start(void);
extern void MX_Gtwy_Contr_Machine_Lock_Init(void);
extern void MX_Gtwy_Control_Machine_Lock(void);
extern void MX_Gtwy_C_Throttle_Command_Init(void);
extern void MX_Gtwy_Contro_Throttle_Command(void);

#endif                                 // RTW_HEADER_mod_System_h_

//
//  [EOF]

