//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gtwy_Control


#ifndef RTW_HEADER_MX_Gtwy_Control_types_h_
#define RTW_HEADER_MX_Gtwy_Control_types_h_

// Forward declaration for rtModel
typedef struct tag_RTM_MX_Gtwy_Control RT_MODEL_MX_Gtwy_Control;

#endif                                 // RTW_HEADER_MX_Gtwy_Control_types_h_

//
//  [EOF]

