//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gtwy_Control


#ifndef RTW_HEADER_MX_Gtwy_Control_private_h_
#define RTW_HEADER_MX_Gtwy_Control_private_h_
#include "rtwtypes.h"

// Includes for objects with custom storage classes.
#include "cdata.h"
#include "defines.h"
#include "hw_fin.h"
#include "ap_can.h"
#include "ap_eeprom.h"
#ifndef PORTABLE_WORDSIZES
#ifndef UCHAR_MAX
#include <limits.h>
#endif

#if ( UCHAR_MAX != (0xFFU) ) || ( SCHAR_MAX != (0x7F) )
#error Code was generated for compiler with different sized uchar/char. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( USHRT_MAX != (0xFFFFU) ) || ( SHRT_MAX != (0x7FFF) )
#error Code was generated for compiler with different sized ushort/short. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( UINT_MAX != (0xFFFFFFFFU) ) || ( INT_MAX != (0x7FFFFFFF) )
#error Code was generated for compiler with different sized uint/int. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( ULONG_MAX != (0xFFFFFFFFU) ) || ( LONG_MAX != (0x7FFFFFFF) )
#error Code was generated for compiler with different sized ulong/long. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif
#endif                                 // PORTABLE_WORDSIZES

// Imported (extern) block signals
extern uint8_T pwd_Keyless[5];         // '<S630>/Panel_Lock'
extern uint16_T ain_Console;           // '<Root>/ain_Console'
extern uint16_T ain_SensorSupply1;     // '<Root>/ain_SensorSupply1'
extern uint16_T ain_SensorSupply2;     // '<Root>/ain_SensorSupply2'
extern uint16_T ain_OffsetPot;         // '<Root>/ain_OffsetPot'
extern uint16_T ain_VBattery;          // '<Root>/ain_VBattery'
extern uint16_T ain_SwitchedPower;     // '<Root>/ain_SwitchedPower'
extern uint16_T ain_ECT;               // '<Root>/ain_ECT'
extern uint16_T ain_FuelLevel;         // '<Root>/ain_FuelLevel'
extern uint16_T ain_AuxPot;            // '<Root>/ain_AuxPot'
extern uint16_T ain_PrecisionReference;// '<Root>/ain_PrecisionReference'
extern uint16_T ain_LoadMoment;        // '<Root>/ain_LoadMoment'
extern uint16_T ain_ThrottlePrimary;   // '<Root>/ain_ThrottlePrimary'
extern uint16_T ain_Aux2FlowControl;   // '<Root>/ain_Aux2FlowControl'
extern uint8_T din_AirFilter;          // '<Root>/din_AirFilter'
extern uint8_T din_HCFilter1;          // '<Root>/din_HCFilter1'
extern uint8_T din_ACOn;               // '<Root>/din_ACOn'
extern uint8_T din_TwoSpeedSwitch;     // '<Root>/din_TwoSpeedSwitch'
extern boolean_T dfbk_StarterOutput;   // '<Root>/dfbk_StarterOutput'
extern uint8_T din_RunEnter;           // '<Root>/din_RunEnter'
extern uint8_T din_RemoteKey;          // '<Root>/din_RemoteKey'
extern uint8_T din_EngineStart;        // '<Root>/din_EngineStart'
extern boolean_T din_SwPowerRelay;     // '<Root>/din_SwPowerRelay'
extern boolean_T dfbk_SwPowerOutput;   // '<Root>/dfbk_SwPowerOutput'
extern boolean_T din_GlowPlugRelay;    // '<Root>/din_GlowPlugRelay'
extern boolean_T dfbk_GlowPlugOutput;  // '<Root>/dfbk_GlowPlugOutput'
extern boolean_T din_FuelPriRelay;     // '<Root>/din_FuelPriRelay'
extern boolean_T dfbk_FuelPriOutput;   // '<Root>/dfbk_FuelPriOutput'
extern boolean_T din_StarterRelay;     // '<Root>/din_StarterRelay'
extern uint8_T dfbk_Buzzer;            // '<Root>/dfbk_Buzzer'
extern boolean_T dfbk_LightsOutput;    // '<Root>/dfbk_LightsOutput'
extern boolean_T dfbk_HydExchange;     // '<Root>/dfbk_HydExchange'
extern boolean_T din_HVACRelay;        // '<Root>/din_HVACRelay'
extern boolean_T dfbk_HVACOutput;      // '<Root>/dfbk_HVACOutput'
extern uint8_T din_Detent;             // '<Root>/din_Detent'
extern boolean_T din_LightsRelay;      // '<Root>/din_LightsRelay'
extern boolean_T din_SecondAuxSw;      // '<Root>/din_SecondAuxSw'
extern boolean_T din_PBValveRelay;     // '<Root>/din_PBValveRelay'
extern boolean_T dfbk_PBValveOutput;   // '<Root>/dfbk_PBValveOutput'
extern boolean_T din_OWDEnableSw;      // '<Root>/din_OWDEnableSw'
extern boolean_T din_LeftHandleSelectSw;// '<Root>/din_LeftHandleSelectSw'
extern uint16_T adin_HOT;              // '<Root>/adin_HOT'
extern uint16_T adin_EOP;              // '<Root>/adin_EOP'
extern uint16_T adin_LoadSense;        // '<Root>/adin_LoadSense'
extern uint16_T adin_TravelPressureSwitch;// '<Root>/adin_TravelPressureSwitch'
extern uint16_T afbk_HydEnable;        // '<Root>/afbk_HydEnable'
extern uint16_T afbk_OffsetRod;        // '<Root>/afbk_OffsetRod'
extern uint16_T afbk_AuxRod;           // '<Root>/afbk_AuxRod'
extern uint16_T afbk_FuelSec;          // '<Root>/afbk_FuelSec'
extern uint16_T afbk_TwoSpeed;         // '<Root>/afbk_TwoSpeed'
extern uint16_T afbk_TwoSpeedSecondary;// '<Root>/afbk_TwoSpeedSecondary'
extern uint16_T afbk_OffsetBase;       // '<Root>/afbk_OffsetBase'
extern uint16_T afbk_AuxBase;          // '<Root>/afbk_AuxBase'
extern uint16_T afbk_DumpValve;        // '<Root>/afbk_DumpValve'
extern uint16_T afbk_HydBypass;        // '<Root>/afbk_HydBypass'
extern uint16_T afbk_Diverter;         // '<Root>/afbk_Diverter'
extern uint16_T ifbk_HydEnable;        // '<Root>/ifbk_HydEnable'
extern uint16_T ifbk_OffsetRod;        // '<Root>/ifbk_OffsetRod'
extern uint16_T ifbk_AuxRod;           // '<Root>/ifbk_AuxRod'
extern uint16_T ifbk_OffsetBase;       // '<Root>/ifbk_OffsetBase'
extern uint16_T ifbk_AuxBase;          // '<Root>/ifbk_AuxBase'
extern uint16_T ifbk_DumpValve;        // '<Root>/ifbk_DumpValve'
extern uint16_T ifbk_HydBypass;        // '<Root>/ifbk_HydBypass'
extern uint16_T ifbk_Diverter;         // '<Root>/ifbk_Diverter'
extern uint8_T msg_PanelButtonState[8];// '<Root>/msg_PanelButtonState'
extern uint16_T msgAge_StdDisplay;     // '<Root>/msgAge_StdDisplay'
extern uint16_T msgAge_Secondary;      // '<Root>/msgAge_Secondary'
extern uint8_T can_sec_spare1;         // '<Root>/can_sec_spare1'
extern uint8_T can_sec_spare2;         // '<Root>/can_sec_spare2'
extern uint8_T btn_SnakeEyes;          // '<Root>/btn_SnakeEyes'
extern uint16_T delay_DepthBeep;       // '<Root>/delay_DepthBeep'
extern uint8_T state_DepthBeep;        // '<Root>/state_DepthBeep'
extern boolean_T can_OffsetSelectSw;   // '<Root>/can_OffsetSelectSw'
extern boolean_T can_RightHandleSelectSw;// '<Root>/can_RightHandleSelectSw'
extern uint16_T msgAge_Throttle;       // '<Root>/msgAge_Throttle'
extern uint16_T fdbk_CANThrottle;      // '<Root>/fdbk_CANThrottle'
extern uint8_T can_ST_EngineStart;     // '<Root>/can_ST_EngineStart'
extern uint8_T state_ST_CAN;           // '<Root>/state_ST_CAN'
extern uint8_T can_ST_EStop;           // '<Root>/can_ST_EStop'
extern uint8_T cmd_AuxEnable_ST;       // '<Root>/cmd_AuxEnable_ST'
extern uint8_T ecu_EOP;                // '<Root>/ecu_EOP'
extern uint16_T ecu_ECT;               // '<Root>/ecu_ECT'
extern uint16_T ecu_EngineSpeed;       // '<Root>/ecu_EngineSpeed'
extern uint8_T state_ecuECT;           // '<Root>/state_ecuECT'
extern uint8_T state_ecuEOP;           // '<Root>/state_ecuEOP'
extern uint8_T ecu_GlowPlug;           // '<Root>/ecu_GlowPlug'
extern uint16_T msgAge_ECU;            // '<Root>/msgAge_ECU'
extern uint8_T ecu_EngineStarterMode;  // '<Root>/ecu_EngineStarterMode'
extern uint16_T ecu_isocMaxRPM;        // '<Root>/ecu_isocMaxRPM'
extern uint16_T ecu_isocMinRPM;        // '<Root>/ecu_isocMinRPM'
extern int8_T ecu_PercentTorque;       // '<Root>/ecu_PercentTorque'
extern uint16_T lamp_Engine;           // '<Root>/lamp_Engine'
extern uint8_T ecu_HP;                 // '<Root>/ecu_HP'
extern uint16_T can_FuelTemp;          // '<Root>/can_FuelTemp'
extern uint16_T ecu_EOT;               // '<Root>/ecu_EOT'
extern uint8_T state_DeluxeG5;         // '<Root>/state_DeluxeG5'
extern uint8_T flow_Aux1Percent;       // '<Root>/flow_Aux1Percent'
extern uint8_T flow_Aux2Percent;       // '<Root>/flow_Aux2Percent'
extern uint8_T flow_Aux4Percent;       // '<Root>/flow_Aux4Percent'
extern uint8_T flow_OffsetPercent;     // '<Root>/flow_OffsetPercent'
extern uint8_T msg_DeluxeButtons[5];   // '<Root>/msg_DeluxeButtons'
extern uint8_T can_Keypad[3];          // '<Root>/can_Keypad'
extern uint8_T state_KeylessPanel;     // '<Root>/state_KeylessPanel'
extern uint8_T msg_BJM2Left[8];        // '<Root>/msg_BJM2Left'
extern uint16_T msgAge_BJM2Left;       // '<Root>/msgAge_BJM2Left'
extern uint8_T msg_BJM2Right[8];       // '<Root>/msg_BJM2Right'
extern uint16_T msgAge_BJM2Right;      // '<Root>/msgAge_BJM2Right'
extern uint8_T can_ACD_EngineStart;    // '<Root>/can_ACD_EngineStart'
extern uint8_T state_ACD_CAN;          // '<Root>/state_ACD_CAN'
extern uint8_T can_ACD_EStop;          // '<Root>/can_ACD_EStop'
extern uint8_T can_ACD_AuxCommand;     // '<Root>/can_ACD_AuxCommand'
extern uint8_T cmd_AuxEnable_ACD;      // '<Root>/cmd_AuxEnable_ACD'
extern uint16_T msgAge_DeluxeG55;      // '<Root>/msgAge_DeluxeG55'
extern uint8_T dlx_G55_AutoIdle;       // '<Root>/dlx_G55_AutoIdle'
extern uint8_T dlx_G55_EcoMode;        // '<Root>/dlx_G55_EcoMode'
extern uint8_T dlx_G55_AutoIdleTime;   // '<Root>/dlx_G55_AutoIdleTime'
extern uint8_T auth_DeluxeG55;         // '<Root>/auth_DeluxeG55'
extern uint8_T state_DeluxeG55;        // '<Root>/state_DeluxeG55'
extern uint16_T msgAge_JogShuttle;     // '<Root>/msgAge_JogShuttle'
extern uint8_T btn_JogShuttleAux;      // '<Root>/btn_JogShuttleAux'
extern uint8_T btn_JogShuttleLights;   // '<Root>/btn_JogShuttleLights'
extern uint8_T can_KeylessEntry[3];    // '<Root>/can_KeylessEntry'
extern uint16_T msgAge_KeylessEntry;   // '<Root>/msgAge_KeylessEntry'
extern uint32_T freq_EngineSpeed;      // '<Root>/freq_EngineSpeed'
extern uint8_T ee_OwnerPassword[5];    // '<Root>/ee_OwnerPassword'
extern uint8_T ee_MasterPassword[5];   // '<Root>/ee_MasterPassword'
extern uint8_T state_ConstantData;     // '<Root>/state_ConstantData'
extern uint8_T state_TwoSpeedLock;     // '<Root>/state_TwoSpeedLock'
extern uint8_T ddp_MachineLock;        // '<Root>/ddp_MachineLock'
extern uint8_T state_ConsoleTest;      // '<Root>/state_ConsoleTest'
extern uint8_T state_ServiceClock;     // '<Root>/state_ServiceClock'
extern uint8_T state_System;           // '<Root>/state_System'
extern boolean_T flag_InitEERead;      // '<Root>/flag_InitEERead'
extern uint8_T scrn_DeluxePwdFail;     // '<Root>/scrn_DeluxePwdFail'
extern uint32_T actualHourMeter;       // '<Root>/actualHourMeter'
extern uint8_T dv_TurboPrime;          // '<Root>/dv_TurboPrime'
extern uint8_T state_KeylessEntryPassword;// '<Root>/state_KeylessEntryPassword' 
extern uint8_T state_KeylessEntryLock; // '<Root>/state_KeylessEntryLock'
extern uint8_T ee_User1Password[5];    // '<Root>/ee_User1Password'
extern uint8_T ee_User2Password[5];    // '<Root>/ee_User2Password'
extern uint8_T state_Inverter;         // '<Root>/state_Inverter'

// Imported (extern) states
extern uint8_T flag_StdActiveWarn;     // Simulink.Signal object 'flag_StdActiveWarn' 
extern uint8_T state_Buzzer;           // Simulink.Signal object 'state_Buzzer'
void BINARYSEARCH_U16_Near_iL(uint32_T *piLeft, uint16_T u, const uint16_T
  *pData, uint32_T iHi);
void BINARYSEARCH_U16(uint32_T *piLeft, uint32_T *piRght, uint16_T u, const
                      uint16_T *pData, uint32_T iHi);
void INTERPOLATE_U16_U16(uint16_T *pY, uint16_T yL, uint16_T yR, uint16_T x,
  uint16_T xL, uint16_T xR);
void LookUp_U16_U16(uint16_T *pY, const uint16_T *pYData, uint16_T u, const
                    uint16_T *pUData, uint32_T iHi);
void INTERPOLATE_EVEN_U16_U16_SAT(uint16_T *pY, uint16_T yL, uint16_T yR,
  uint16_T xMinusxL, uint16_T xSpacing);
void LookUpEven_U16_U16_SAT(uint16_T *pY, const uint16_T *pYData, uint16_T u,
  uint16_T valueLo, uint32_T iHi, uint16_T uSpacing);
void INTERPOLATE_U16_U16_SAT(uint16_T *pY, uint16_T yL, uint16_T yR, uint16_T x,
  uint16_T xL, uint16_T xR);
void LookUp_U16_U16_SAT(uint16_T *pY, const uint16_T *pYData, uint16_T u, const
  uint16_T *pUData, uint32_T iHi);
void BINARYSEARCH_U16_iL(uint32_T *piLeft, uint16_T u, const uint16_T *pData,
  uint32_T iHi);
void BINARYSEARCH_S16(uint32_T *piLeft, uint32_T *piRght, int16_T u, const
                      int16_T *pData, uint32_T iHi);
void INTERPOLATE_U16_S16(uint16_T *pY, uint16_T yL, uint16_T yR, int16_T x,
  int16_T xL, int16_T xR);
void LookUp_U16_S16(uint16_T *pY, const uint16_T *pYData, int16_T u, const
                    int16_T *pUData, uint32_T iHi);
extern int32_T div_s32(int32_T numerator, int32_T denominator);
extern int16_T div_s16u32(uint32_T numerator, uint32_T denominator);
extern void mul_wide_su32(int32_T in0, uint32_T in1, uint32_T *ptrOutBitsHi,
  uint32_T *ptrOutBitsLo);
extern uint32_T mul_usu32_loSR(int32_T a, uint32_T b, uint32_T aShift);
extern int32_T div_repeat_s32_near(int32_T numerator, int32_T denominator,
  uint32_T nRepeatSub);
extern uint32_T div_u32_near(uint32_T numerator, uint32_T denominator);
extern void mul_wide_s32(int32_T in0, int32_T in1, uint32_T *ptrOutBitsHi,
  uint32_T *ptrOutBitsLo);
extern int32_T mul_s32_hiSR(int32_T a, int32_T b, uint32_T aShift);
extern int32_T div_s32_floor(int32_T numerator, int32_T denominator);

#endif                                 // RTW_HEADER_MX_Gtwy_Control_private_h_

//
//  [EOF]

