//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gateway


#ifndef RTW_HEADER_mod_System_h_
#define RTW_HEADER_mod_System_h_
#ifndef MX_Gateway_COMMON_INCLUDES_
# define MX_Gateway_COMMON_INCLUDES_
#include "rtwtypes.h"
#include "rtw_continuous.h"
#include "rtw_solver.h"
#endif                                 // MX_Gateway_COMMON_INCLUDES_

#include "MX_Gateway_types.h"

extern void MX_Gatewa_Auto_Idle_Enable_Init(void);
extern void MX_Gateway_Auto_Idle_Enable(void);
extern void MX_Gateway_AutoIdle_Init(void);
extern void MX_Gateway_AutoIdle(void);
extern void MX_Gateway_Aux_Enable_Init(void);
extern void MX_Gateway_Aux_Enable(void);
extern void MX_Gateway_CAN_Throttle_Init(void);
extern void MX_Gateway_CAN_Throttle_Update(void);
extern void MX_Gateway_CAN_Throttle(void);
extern void MX_Gatewa_Controller_State_Init(void);
extern void MX_Gateway_Controller_State(void);
extern void MX_Gateway_Derate_Init(void);
extern void MX_Gateway_Derate(void);
extern void MX_Gateway_EMEAControlMode_Init(void);
extern void MX_Gateway_EMEAControlMode(void);
extern void MX_Gate_ElectricAutomation_Init(void);
extern void MX_Gateway_ElectricAutomation(void);
extern void MX_Gateway_Engine_Init(void);
extern void MX_Gateway_Engine(void);
extern void MX_Gateway_Keyless_Entry_Init(void);
extern void MX_Gateway_Keyless_Entry_Reset(void);
extern void MX_Gatewa_Keyless_Entry_Disable(void);
extern void MX_Gateway_Keyless_Entry(void);
extern void MX_Gateway_Keyless_Start_Init(void);
extern void MX_Gateway_Keyless_Start(void);
extern void MX_Gateway_Machine_Lock_Init(void);
extern void MX_Gateway_Machine_Lock(void);
extern void MX_Gatewa_Throttle_Command_Init(void);
extern void MX_Gateway_Throttle_Command(void);

#endif                                 // RTW_HEADER_mod_System_h_

//
//  [EOF]

