//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gateway


#ifndef RTW_HEADER_mod_Panel_h_
#define RTW_HEADER_mod_Panel_h_
#ifndef MX_Gateway_COMMON_INCLUDES_
# define MX_Gateway_COMMON_INCLUDES_
#include "rtwtypes.h"
#include "rtw_continuous.h"
#include "rtw_solver.h"
#endif                                 // MX_Gateway_COMMON_INCLUDES_

#include "MX_Gateway_types.h"

extern void MX_Gateway_AutoIdle_Ind_Init(void);
extern void MX_Gateway_AutoIdle_Ind(void);
extern void MX_Gateway_Aux_Ind_Init(void);
extern void MX_Gateway_Aux_Ind(void);
extern void MX_Gateway_Backlighting_Init(void);
extern void MX_Gateway_Backlighting(void);
extern void MX_Gateway_FrontLight_Init(void);
extern void MX_Gateway_FrontLight(void);
extern void MX_Gate_InformationDisplay_Init(void);
extern void MX_Gateway_InformationDisplay(void);
extern void MX_Gate_Keyless_Indicators_Init(void);
extern void MX_Gateway_Keyless_Indicators(void);
extern void MX_Gateway_mod_AuxIcon(void);
extern void MX_Gateway_mod_BatteryIcon_Init(void);
extern void MX_Gateway_mod_BatteryIcon(void);
extern void MX_Gateway_mod_ECTIcon_Init(void);
extern void MX_Gateway_mod_ECTIcon(void);
extern void MX_Gateway_mod_EngineIcon_Init(void);
extern void MX_Gateway_mod_EngineIcon(void);
extern void MX_Gatew_mod_FuelLevelIcon_Init(void);
extern void MX_Gateway_mod_FuelLevelIcon(void);
extern void MX__mod_GeneralWarningIcon_Init(void);
extern void MX_Gatew_mod_GeneralWarningIcon(void);
extern void MX_Gatewa_mod_GlowPlugIcon_Init(void);
extern void MX_Gateway_mod_GlowPlugIcon(void);
extern void MX_Gateway_mod_HourMeterIcon(void);
extern void MX_Gatew_mod_HydraulicIcon_Init(void);
extern void MX_Gateway_mod_HydraulicIcon(void);
extern void MX_Gateway_mod_JobClock1Icon(void);
extern void MX_Gateway_mod_JobClock2Icon(void);
extern void MX_Gateway_mod_LockoutIcon_Init(void);
extern void MX_Gateway_mod_LockoutIcon(void);
extern void MX_Gateway_mod_RPMIcon_Init(void);
extern void MX_Gateway_mod_RPMIcon(void);
extern void MX_Gatewa_mod_SeatBeltIcon_Init(void);
extern void MX_Gateway_mod_SeatBeltIcon(void);
extern void MX_Gateway_mod_ServiceClockIcon(void);
extern void MX_Gatewa_mod_TwoSpeedIcon_Init(void);
extern void MX_Gateway_mod_TwoSpeedIcon(void);

#endif                                 // RTW_HEADER_mod_Panel_h_

//
//  [EOF]

