//
//  Copyright (c) 2009 Bobcat Company as an unpublished work.
//  All Rights Reserved.
//
//  The information contained herein is confidential property of Bobcat Company.
//  The use, copying, transfer or disclosure of such information is prohibited except
//  by express written agreement with Bobcat Company.
//
//  Code Generated by Simulink Real-Time Workshop
//
//  Simulink model                       : MX_Gateway


#ifndef RTW_HEADER_MX_Gateway_private_h_
#define RTW_HEADER_MX_Gateway_private_h_
#include "rtwtypes.h"

// Includes for objects with custom storage classes.
#include "cdata.h"
#include "defines.h"
#include "hw_fin.h"
#include "ap_can.h"
#include "ap_eeprom.h"

// Private macros used by the generated code to access rtModel
#ifndef rtmIsMajorTimeStep
# define rtmIsMajorTimeStep(rtm)       (((rtm)->Timing.simTimeStep) == MAJOR_TIME_STEP)
#endif

#ifndef rtmIsMinorTimeStep
# define rtmIsMinorTimeStep(rtm)       (((rtm)->Timing.simTimeStep) == MINOR_TIME_STEP)
#endif

#ifndef rtmGetTPtr
# define rtmGetTPtr(rtm)               ((rtm)->Timing.t)
#endif

#ifndef rtmSetTPtr
# define rtmSetTPtr(rtm, val)          ((rtm)->Timing.t = (val))
#endif

#ifndef PORTABLE_WORDSIZES
#ifndef UCHAR_MAX
#include <limits.h>
#endif

#if ( UCHAR_MAX != (0xFFU) ) || ( SCHAR_MAX != (0x7F) )
#error Code was generated for compiler with different sized uchar/char. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( USHRT_MAX != (0xFFFFU) ) || ( SHRT_MAX != (0x7FFF) )
#error Code was generated for compiler with different sized ushort/short. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( UINT_MAX != (0xFFFFFFFFU) ) || ( INT_MAX != (0x7FFFFFFF) )
#error Code was generated for compiler with different sized uint/int. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif

#if ( ULONG_MAX != (0xFFFFFFFFU) ) || ( LONG_MAX != (0x7FFFFFFF) )
#error Code was generated for compiler with different sized ulong/long. \
Consider adjusting Test hardware word size settings on the \
Hardware Implementation pane to match your compiler word sizes as \
defined in limits.h of the compiler. Alternatively, you can \
select the Test hardware is the same as production hardware option and \
select the Enable portable word sizes option on the Code Generation > \
Verification pane for ERT based targets, which will disable the \
preprocessor word size checks.
#endif
#endif                                 // PORTABLE_WORDSIZES

// Used by FromWorkspace Block: '<S16>/FromWs'
#ifndef rtInterpolate
# define rtInterpolate(v1,v2,f1,f2)    (((v1)==(v2))?((double)(v1)): (((f1)*((double)(v1)))+((f2)*((double)(v2)))))
#endif

#ifndef rtRound
# define rtRound(v)                    ( ((v) >= 0) ? floor((v) + 0.5) : ceil((v) - 0.5) )
#endif

// Imported (extern) block signals
extern uint32_T freq_EngineSpeed;      // '<S1>/Data Type Conversion10'
extern uint32_T actualHourMeter;       // '<S1>/Data Type Conversion65'
extern uint16_T msgAge_BJM2Right;      // '<S3>/Constant7'
extern uint16_T msgAge_BJM2Left;       // '<S3>/Constant8'
extern uint16_T can_FuelTemp;          // '<S3>/Data Type Conversion1'
extern uint16_T ecu_ECT;               // '<S3>/Data Type Conversion107'
extern uint16_T ecu_EngineSpeed;       // '<S3>/Data Type Conversion108'
extern uint16_T ecu_isocMinRPM;        // '<S3>/Data Type Conversion12'
extern uint16_T msgAge_ECU;            // '<S3>/Data Type Conversion121'
extern uint16_T lamp_Engine;           // '<S3>/Data Type Conversion13'
extern uint16_T msgAge_DeluxeG55;      // '<S3>/Data Type Conversion15'
extern uint16_T msgAge_StdDisplay;     // '<S3>/Data Type Conversion2'
extern uint16_T msgAge_JogShuttle;     // '<S3>/Data Type Conversion20'
extern uint16_T fdbk_CANThrottle;      // '<S3>/Data Type Conversion27'
extern uint16_T msgAge_KeylessEntry;   // '<S3>/Data Type Conversion29'
extern uint16_T delay_DepthBeep;       // '<S3>/Data Type Conversion3'
extern uint16_T ecu_isocMaxRPM;        // '<S3>/Data Type Conversion4'
extern uint16_T msgAge_Throttle;       // '<S3>/Data Type Conversion49'
extern uint16_T ecu_EOT;               // '<S3>/Data Type Conversion5'
extern uint16_T msgAge_Secondary;      // '<S3>/Data Type Conversion73'
extern uint16_T ain_SensorSupply1;     // '<S1>/Data Type Conversion1'
extern uint16_T adin_TravelPressureSwitch;// '<S1>/Data Type Conversion110'
extern uint16_T ain_VBattery;          // '<S1>/Data Type Conversion15'
extern uint16_T ain_FuelLevel;         // '<S1>/Data Type Conversion17'
extern uint16_T afbk_FuelSec;          // '<S1>/Data Type Conversion19'
extern uint16_T ain_Console;           // '<S1>/Data Type Conversion2'
extern uint16_T ifbk_HydEnable;        // '<S1>/Data Type Conversion20'
extern uint16_T ifbk_OffsetRod;        // '<S1>/Data Type Conversion21'
extern uint16_T afbk_OffsetRod;        // '<S1>/Data Type Conversion22'
extern uint16_T afbk_AuxRod;           // '<S1>/Data Type Conversion23'
extern uint16_T ifbk_AuxRod;           // '<S1>/Data Type Conversion24'
extern uint16_T adin_HOT;              // '<S1>/Data Type Conversion26'
extern uint16_T adin_EOP;              // '<S1>/Data Type Conversion27'
extern uint16_T ain_ECT;               // '<S1>/Data Type Conversion28'
extern uint16_T adin_LoadSense;        // '<S1>/Data Type Conversion29'
extern uint16_T ain_OffsetPot;         // '<S1>/Data Type Conversion3'
extern uint16_T ifbk_HydBypass;        // '<S1>/Data Type Conversion30'
extern uint16_T ain_PrecisionReference;// '<S1>/Data Type Conversion34'
extern uint16_T ain_AuxPot;            // '<S1>/Data Type Conversion36'
extern uint16_T ain_SensorSupply2;     // '<S1>/Data Type Conversion4'
extern uint16_T ifbk_DumpValve;        // '<S1>/Data Type Conversion50'
extern uint16_T afbk_DumpValve;        // '<S1>/Data Type Conversion51'
extern uint16_T afbk_HydBypass;        // '<S1>/Data Type Conversion52'
extern uint16_T afbk_OffsetBase;       // '<S1>/Data Type Conversion56'
extern uint16_T ifbk_OffsetBase;       // '<S1>/Data Type Conversion57'
extern uint16_T ifbk_Diverter;         // '<S1>/Data Type Conversion58'
extern uint16_T afbk_TwoSpeed;         // '<S1>/Data Type Conversion59'
extern uint16_T ain_SwitchedPower;     // '<S1>/Data Type Conversion6'
extern uint16_T afbk_TwoSpeedSecondary;// '<S1>/Data Type Conversion60'
extern uint16_T afbk_HydEnable;        // '<S1>/Data Type Conversion61'
extern uint16_T afbk_Diverter;         // '<S1>/Data Type Conversion62'
extern uint16_T ain_LoadMoment;        // '<S1>/Data Type Conversion63'
extern uint16_T ain_ThrottlePrimary;   // '<S1>/Data Type Conversion66'
extern uint16_T afbk_AuxBase;          // '<S1>/Data Type Conversion69'
extern uint16_T ifbk_AuxBase;          // '<S1>/Data Type Conversion70'
extern uint16_T ain_Aux2FlowControl;   // '<S1>/Data Type Conversion71'
extern int8_T ecu_PercentTorque;       // '<S3>/Data Type Conversion14'
extern uint8_T can_Keypad[3];          // '<S3>/Constant'
extern uint8_T msg_DeluxeButtons[5];   // '<S3>/Constant1'
extern uint8_T can_KeylessEntry[3];    // '<S3>/Constant2'
extern uint8_T msg_PanelButtonState[8];// '<S3>/Constant3'
extern uint8_T msg_BJM2Right[8];       // '<S3>/Constant4'
extern uint8_T msg_BJM2Left[8];        // '<S3>/Constant6'
extern uint8_T can_ST_EStop;           // '<S3>/Data Type Conversion10'
extern uint8_T ecu_EOP;                // '<S3>/Data Type Conversion105'
extern uint8_T state_KeylessPanel;     // '<S3>/Data Type Conversion106'
extern uint8_T cmd_AuxEnable_ST;       // '<S3>/Data Type Conversion11'
extern uint8_T state_ecuECT;           // '<S3>/Data Type Conversion114'
extern uint8_T state_ecuEOP;           // '<S3>/Data Type Conversion115'
extern uint8_T ecu_GlowPlug;           // '<S3>/Data Type Conversion116'
extern uint8_T dlx_G55_AutoIdle;       // '<S3>/Data Type Conversion16'
extern uint8_T dlx_G55_EcoMode;        // '<S3>/Data Type Conversion17'
extern uint8_T dlx_G55_AutoIdleTime;   // '<S3>/Data Type Conversion18'
extern uint8_T flow_Aux1Percent;       // '<S3>/Data Type Conversion19'
extern uint8_T can_sec_spare1;         // '<S3>/Data Type Conversion21'
extern uint8_T can_sec_spare2;         // '<S3>/Data Type Conversion22'
extern uint8_T btn_SnakeEyes;          // '<S3>/Data Type Conversion23'
extern uint8_T btn_JogShuttleAux;      // '<S3>/Data Type Conversion24'
extern uint8_T btn_JogShuttleLights;   // '<S3>/Data Type Conversion25'
extern uint8_T auth_DeluxeG55;         // '<S3>/Data Type Conversion28'
extern uint8_T can_ACD_EStop;          // '<S3>/Data Type Conversion32'
extern uint8_T can_ACD_AuxCommand;     // '<S3>/Data Type Conversion33'
extern uint8_T can_ACD_EngineStart;    // '<S3>/Data Type Conversion34'
extern uint8_T state_ACD_CAN;          // '<S3>/Data Type Conversion35'
extern uint8_T cmd_AuxEnable_ACD;      // '<S3>/Data Type Conversion36'
extern uint8_T ecu_HP;                 // '<S3>/Data Type Conversion37'
extern uint8_T state_DeluxeG55;        // '<S3>/Data Type Conversion38'
extern uint8_T flow_Aux2Percent;       // '<S3>/Data Type Conversion39'
extern uint8_T flow_Aux4Percent;       // '<S3>/Data Type Conversion40'
extern uint8_T flow_OffsetPercent;     // '<S3>/Data Type Conversion41'
extern uint8_T ecu_EngineStarterMode;  // '<S3>/Data Type Conversion6'
extern uint8_T state_DepthBeep;        // '<S3>/Data Type Conversion7'
extern uint8_T state_DeluxeG5;         // '<S3>/Data Type Conversion72'
extern uint8_T can_ST_EngineStart;     // '<S3>/Data Type Conversion8'
extern uint8_T state_ST_CAN;           // '<S3>/Data Type Conversion9'
extern uint8_T state_Inverter;         // '<S4>/Data Type Conversion1'
extern uint8_T ee_OwnerPassword[5];    // '<S1>/Constant1'
extern uint8_T ee_MasterPassword[5];   // '<S1>/Constant2'
extern uint8_T ee_User1Password[5];    // '<S1>/Constant3'
extern uint8_T ee_User2Password[5];    // '<S1>/Constant4'
extern uint8_T state_ConsoleTest;      // '<S1>/Data Type Conversion101'
extern uint8_T din_AirFilter;          // '<S1>/Data Type Conversion12'
extern uint8_T din_HCFilter1;          // '<S1>/Data Type Conversion13'
extern uint8_T din_TwoSpeedSwitch;     // '<S1>/Data Type Conversion14'
extern uint8_T dfbk_Buzzer;            // '<S1>/Data Type Conversion33'
extern uint8_T state_TwoSpeedLock;     // '<S1>/Data Type Conversion37'
extern uint8_T ddp_MachineLock;        // '<S1>/Data Type Conversion38'
extern uint8_T din_Detent;             // '<S1>/Data Type Conversion42'
extern uint8_T state_ConstantData;     // '<S1>/Data Type Conversion45'
extern uint8_T state_ServiceClock;     // '<S1>/Data Type Conversion47'
extern uint8_T state_System;           // '<S1>/Data Type Conversion48'
extern uint8_T scrn_DeluxePwdFail;     // '<S1>/Data Type Conversion49'
extern uint8_T din_RemoteKey;          // '<S1>/Data Type Conversion5'
extern uint8_T dv_TurboPrime;          // '<S1>/Data Type Conversion67'
extern uint8_T din_EngineStart;        // '<S1>/Data Type Conversion7'
extern uint8_T state_KeylessEntryPassword;// '<S1>/Data Type Conversion72'
extern uint8_T state_KeylessEntryLock; // '<S1>/Data Type Conversion73'
extern uint8_T din_ACOn;               // '<S1>/Data Type Conversion8'
extern uint8_T din_RunEnter;           // '<S1>/Data Type Conversion9'
extern uint8_T pwd_Keyless[5];         // '<S648>/Panel_Lock'
extern boolean_T can_OffsetSelectSw;   // '<S3>/Data Type Conversion30'
extern boolean_T can_RightHandleSelectSw;// '<S3>/Data Type Conversion31'
extern boolean_T flag_InitEERead;      // '<S1>/Data Type Conversion103'
extern boolean_T dfbk_StarterOutput;   // '<S1>/Data Type Conversion11'
extern boolean_T dfbk_LightsOutput;    // '<S1>/Data Type Conversion16'
extern boolean_T din_SecondAuxSw;      // '<S1>/Data Type Conversion18'
extern boolean_T dfbk_HydExchange;     // '<S1>/Data Type Conversion25'
extern boolean_T dfbk_SwPowerOutput;   // '<S1>/Data Type Conversion31'
extern boolean_T din_SwPowerRelay;     // '<S1>/Data Type Conversion32'
extern boolean_T dfbk_HVACOutput;      // '<S1>/Data Type Conversion35'
extern boolean_T din_PBValveRelay;     // '<S1>/Data Type Conversion39'
extern boolean_T dfbk_GlowPlugOutput;  // '<S1>/Data Type Conversion40'
extern boolean_T din_GlowPlugRelay;    // '<S1>/Data Type Conversion41'
extern boolean_T dfbk_FuelPriOutput;   // '<S1>/Data Type Conversion43'
extern boolean_T din_FuelPriRelay;     // '<S1>/Data Type Conversion44'
extern boolean_T din_StarterRelay;     // '<S1>/Data Type Conversion46'
extern boolean_T din_LightsRelay;      // '<S1>/Data Type Conversion53'
extern boolean_T dfbk_PBValveOutput;   // '<S1>/Data Type Conversion54'
extern boolean_T din_OWDEnableSw;      // '<S1>/Data Type Conversion55'
extern boolean_T din_HVACRelay;        // '<S1>/Data Type Conversion64'
extern boolean_T din_LeftHandleSelectSw;// '<S1>/Data Type Conversion68'

// Imported (extern) states
extern uint8_T flag_StdActiveWarn;     // Simulink.Signal object 'flag_StdActiveWarn' 
extern uint8_T state_Buzzer;           // Simulink.Signal object 'state_Buzzer'
void BINARYSEARCH_U16_Near_iL(uint32_T *piLeft, uint16_T u, const uint16_T
  *pData, uint32_T iHi);
void BINARYSEARCH_U16(uint32_T *piLeft, uint32_T *piRght, uint16_T u, const
                      uint16_T *pData, uint32_T iHi);
void INTERPOLATE_U16_U16(uint16_T *pY, uint16_T yL, uint16_T yR, uint16_T x,
  uint16_T xL, uint16_T xR);
void LookUp_U16_U16(uint16_T *pY, const uint16_T *pYData, uint16_T u, const
                    uint16_T *pUData, uint32_T iHi);
void INTERPOLATE_EVEN_U16_U16_SAT(uint16_T *pY, uint16_T yL, uint16_T yR,
  uint16_T xMinusxL, uint16_T xSpacing);
void LookUpEven_U16_U16_SAT(uint16_T *pY, const uint16_T *pYData, uint16_T u,
  uint16_T valueLo, uint32_T iHi, uint16_T uSpacing);
void INTERPOLATE_U16_U16_SAT(uint16_T *pY, uint16_T yL, uint16_T yR, uint16_T x,
  uint16_T xL, uint16_T xR);
void LookUp_U16_U16_SAT(uint16_T *pY, const uint16_T *pYData, uint16_T u, const
  uint16_T *pUData, uint32_T iHi);
void BINARYSEARCH_U16_iL(uint32_T *piLeft, uint16_T u, const uint16_T *pData,
  uint32_T iHi);
void BINARYSEARCH_S16(uint32_T *piLeft, uint32_T *piRght, int16_T u, const
                      int16_T *pData, uint32_T iHi);
void INTERPOLATE_U16_S16(uint16_T *pY, uint16_T yL, uint16_T yR, int16_T x,
  int16_T xL, int16_T xR);
void LookUp_U16_S16(uint16_T *pY, const uint16_T *pYData, int16_T u, const
                    int16_T *pUData, uint32_T iHi);
extern int32_T div_s32(int32_T numerator, int32_T denominator);
extern int16_T div_s16u32(uint32_T numerator, uint32_T denominator);
extern void mul_wide_su32(int32_T in0, uint32_T in1, uint32_T *ptrOutBitsHi,
  uint32_T *ptrOutBitsLo);
extern uint32_T mul_usu32_loSR(int32_T a, uint32_T b, uint32_T aShift);
extern int32_T div_repeat_s32_near(int32_T numerator, int32_T denominator,
  uint32_T nRepeatSub);
extern uint32_T div_u32_near(uint32_T numerator, uint32_T denominator);
extern void mul_wide_s32(int32_T in0, int32_T in1, uint32_T *ptrOutBitsHi,
  uint32_T *ptrOutBitsLo);
extern int32_T mul_s32_hiSR(int32_T a, int32_T b, uint32_T aShift);
extern int32_T div_s32_floor(int32_T numerator, int32_T denominator);

#endif                                 // RTW_HEADER_MX_Gateway_private_h_

//
//  [EOF]

